"""Generate ReplayExport/BuildPieces.g.cs: one export-group class per build-piece path.

FortniteReplayReader only defines a handful of build paths, at Debug parse mode,
so piece properties (owner, team, health, editing player) are otherwise skipped.
Add new shapes here when actor_classes.csv shows unseen PBWA_* classes, then rerun:

    uv run python ingest/gen_build_pieces.py
"""

from pathlib import Path

MATERIALS = [("Wood", "W"), ("Stone", "S"), ("Metal", "M")]
SHAPES = sorted({
    "Solid", "Floor", "StairW", "RoofC",  # unedited wall, floor, stair, cone
    "Archway", "ArchwayLarge", "BalconyI", "BalconyS", "Brace", "DoorC", "DoorSide", "HalfWallS",
    "RoofO", "RoofS", "RoofWall", "StairF", "WindowC", "WindowSide", "Windows", "WindowsC", "WindowsSide",
})

HEADER = """\
// <auto-generated> by ingest/gen_build_pieces.py. Do not edit by hand.
using FortniteReplayReader.Models.NetFieldExports.Vehicles;
using Unreal.Core.Attributes;
using Unreal.Core.Models.Enums;

namespace ReplayExport.BuildPieces;
"""


def main() -> None:
    lines = [HEADER]
    for folder, m in MATERIALS:
        for shape in SHAPES:
            cls = f"PBWA_{m}1_{shape}"
            path = f"/Game/Building/ActorBlueprints/Player/{folder}/L1/{cls}.{cls}_C"
            lines.append(
                f'[NetFieldExportGroup("{path}", minimalParseMode: ParseMode.Minimal)] '
                f"public class {cls} : BaseBuild {{ }}"
            )
    out = Path(__file__).parent / "ReplayExport" / "BuildPieces.g.cs"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{len(MATERIALS) * len(SHAPES)} classes -> {out}")


if __name__ == "__main__":
    main()
