// <auto-generated> by ingest/gen_build_pieces.py. Do not edit by hand.
using FortniteReplayReader.Models.NetFieldExports.Vehicles;
using Unreal.Core.Attributes;
using Unreal.Core.Models.Enums;

namespace ReplayExport.BuildPieces;

[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Wood/L1/PBWA_W1_Archway.PBWA_W1_Archway_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_W1_Archway : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Wood/L1/PBWA_W1_ArchwayLarge.PBWA_W1_ArchwayLarge_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_W1_ArchwayLarge : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Wood/L1/PBWA_W1_BalconyI.PBWA_W1_BalconyI_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_W1_BalconyI : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Wood/L1/PBWA_W1_BalconyS.PBWA_W1_BalconyS_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_W1_BalconyS : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Wood/L1/PBWA_W1_Brace.PBWA_W1_Brace_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_W1_Brace : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Wood/L1/PBWA_W1_DoorC.PBWA_W1_DoorC_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_W1_DoorC : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Wood/L1/PBWA_W1_DoorSide.PBWA_W1_DoorSide_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_W1_DoorSide : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Wood/L1/PBWA_W1_Floor.PBWA_W1_Floor_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_W1_Floor : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Wood/L1/PBWA_W1_HalfWallS.PBWA_W1_HalfWallS_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_W1_HalfWallS : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Wood/L1/PBWA_W1_RoofC.PBWA_W1_RoofC_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_W1_RoofC : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Wood/L1/PBWA_W1_RoofO.PBWA_W1_RoofO_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_W1_RoofO : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Wood/L1/PBWA_W1_RoofS.PBWA_W1_RoofS_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_W1_RoofS : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Wood/L1/PBWA_W1_RoofWall.PBWA_W1_RoofWall_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_W1_RoofWall : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Wood/L1/PBWA_W1_Solid.PBWA_W1_Solid_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_W1_Solid : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Wood/L1/PBWA_W1_StairF.PBWA_W1_StairF_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_W1_StairF : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Wood/L1/PBWA_W1_StairW.PBWA_W1_StairW_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_W1_StairW : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Wood/L1/PBWA_W1_WindowC.PBWA_W1_WindowC_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_W1_WindowC : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Wood/L1/PBWA_W1_WindowSide.PBWA_W1_WindowSide_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_W1_WindowSide : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Wood/L1/PBWA_W1_Windows.PBWA_W1_Windows_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_W1_Windows : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Wood/L1/PBWA_W1_WindowsC.PBWA_W1_WindowsC_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_W1_WindowsC : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Wood/L1/PBWA_W1_WindowsSide.PBWA_W1_WindowsSide_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_W1_WindowsSide : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Stone/L1/PBWA_S1_Archway.PBWA_S1_Archway_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_S1_Archway : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Stone/L1/PBWA_S1_ArchwayLarge.PBWA_S1_ArchwayLarge_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_S1_ArchwayLarge : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Stone/L1/PBWA_S1_BalconyI.PBWA_S1_BalconyI_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_S1_BalconyI : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Stone/L1/PBWA_S1_BalconyS.PBWA_S1_BalconyS_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_S1_BalconyS : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Stone/L1/PBWA_S1_Brace.PBWA_S1_Brace_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_S1_Brace : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Stone/L1/PBWA_S1_DoorC.PBWA_S1_DoorC_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_S1_DoorC : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Stone/L1/PBWA_S1_DoorSide.PBWA_S1_DoorSide_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_S1_DoorSide : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Stone/L1/PBWA_S1_Floor.PBWA_S1_Floor_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_S1_Floor : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Stone/L1/PBWA_S1_HalfWallS.PBWA_S1_HalfWallS_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_S1_HalfWallS : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Stone/L1/PBWA_S1_RoofC.PBWA_S1_RoofC_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_S1_RoofC : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Stone/L1/PBWA_S1_RoofO.PBWA_S1_RoofO_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_S1_RoofO : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Stone/L1/PBWA_S1_RoofS.PBWA_S1_RoofS_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_S1_RoofS : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Stone/L1/PBWA_S1_RoofWall.PBWA_S1_RoofWall_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_S1_RoofWall : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Stone/L1/PBWA_S1_Solid.PBWA_S1_Solid_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_S1_Solid : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Stone/L1/PBWA_S1_StairF.PBWA_S1_StairF_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_S1_StairF : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Stone/L1/PBWA_S1_StairW.PBWA_S1_StairW_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_S1_StairW : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Stone/L1/PBWA_S1_WindowC.PBWA_S1_WindowC_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_S1_WindowC : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Stone/L1/PBWA_S1_WindowSide.PBWA_S1_WindowSide_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_S1_WindowSide : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Stone/L1/PBWA_S1_Windows.PBWA_S1_Windows_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_S1_Windows : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Stone/L1/PBWA_S1_WindowsC.PBWA_S1_WindowsC_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_S1_WindowsC : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Stone/L1/PBWA_S1_WindowsSide.PBWA_S1_WindowsSide_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_S1_WindowsSide : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Metal/L1/PBWA_M1_Archway.PBWA_M1_Archway_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_M1_Archway : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Metal/L1/PBWA_M1_ArchwayLarge.PBWA_M1_ArchwayLarge_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_M1_ArchwayLarge : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Metal/L1/PBWA_M1_BalconyI.PBWA_M1_BalconyI_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_M1_BalconyI : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Metal/L1/PBWA_M1_BalconyS.PBWA_M1_BalconyS_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_M1_BalconyS : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Metal/L1/PBWA_M1_Brace.PBWA_M1_Brace_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_M1_Brace : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Metal/L1/PBWA_M1_DoorC.PBWA_M1_DoorC_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_M1_DoorC : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Metal/L1/PBWA_M1_DoorSide.PBWA_M1_DoorSide_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_M1_DoorSide : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Metal/L1/PBWA_M1_Floor.PBWA_M1_Floor_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_M1_Floor : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Metal/L1/PBWA_M1_HalfWallS.PBWA_M1_HalfWallS_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_M1_HalfWallS : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Metal/L1/PBWA_M1_RoofC.PBWA_M1_RoofC_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_M1_RoofC : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Metal/L1/PBWA_M1_RoofO.PBWA_M1_RoofO_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_M1_RoofO : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Metal/L1/PBWA_M1_RoofS.PBWA_M1_RoofS_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_M1_RoofS : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Metal/L1/PBWA_M1_RoofWall.PBWA_M1_RoofWall_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_M1_RoofWall : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Metal/L1/PBWA_M1_Solid.PBWA_M1_Solid_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_M1_Solid : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Metal/L1/PBWA_M1_StairF.PBWA_M1_StairF_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_M1_StairF : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Metal/L1/PBWA_M1_StairW.PBWA_M1_StairW_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_M1_StairW : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Metal/L1/PBWA_M1_WindowC.PBWA_M1_WindowC_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_M1_WindowC : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Metal/L1/PBWA_M1_WindowSide.PBWA_M1_WindowSide_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_M1_WindowSide : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Metal/L1/PBWA_M1_Windows.PBWA_M1_Windows_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_M1_Windows : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Metal/L1/PBWA_M1_WindowsC.PBWA_M1_WindowsC_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_M1_WindowsC : BaseBuild { }
[NetFieldExportGroup("/Game/Building/ActorBlueprints/Player/Metal/L1/PBWA_M1_WindowsSide.PBWA_M1_WindowsSide_C", minimalParseMode: ParseMode.Minimal)] public class PBWA_M1_WindowsSide : BaseBuild { }
